### ISSUE TITLE
No method _set

### ISSUE THREAD

**Issue by winkler1** [zordius/fluxex#1]
Hi,
 This looks interesting... tried examples/04-infinite, and got this when going to localhost://3001:

TypeError: Object {} has no method '_set'
    at FluxexStore.module.exports.initialize (/Users/Jeff/repos/ghtemp/examples/04-infinite-scroll/stores/search.js:5:14)
    at FluxexStore.FluxexObject (/Users/Jeff/repos/ghtemp/examples/04-infinite-scroll/node_modules/fluxex/lib/fluxobj.js:18:14)
    at new FluxexStore (/Users/Jeff/repos/ghtemp/examples/04-infinite-scroll/node_modules/fluxex/lib/fluxstore.js:15:18)
    at FluxexStore.S (/Users/Jeff/repos/ghtemp/examples/04-infinite-scroll/node_modules/fluxex/lib/fluxex.js:104:25)
    at FluxexApp.Object.assign.createStore (/Users/Jeff/repos/ghtemp/examples/04-infinite-scroll/node_modules/fluxex/lib/fluxex.js:107:16)
    at FluxexApp.Object.assign.initStore (/Users/Jeff/repos/ghtemp/examples/04-infinite-scroll/node_modules/fluxex/lib/fluxex.js:90:40)
    at FluxexApp.Fluxex (/Users/Jeff/repos/ghtemp/examples/04-infinite-scroll/node_modules/fluxex/lib/fluxex.js:22:10)
    at new FluxexApp (/Users/Jeff/repos/ghtemp/examples/04-infinite-scroll/node_modules/fluxex/index.js:23:16)
    at /Users/Jeff/repos/ghtemp/examples/04-infinite-scroll/node_modules/fluxex/extra/server.js:12:14
    at Layer.handle [as handle_request](/Users/Jeff/repos/ghtemp/examples/04-infinite-scroll/node_modules/express/lib/router/layer.js:82:5)

**Comment by zordius** [comment]
Well, we changed our store API to prevent people miss-use `.get()` and `.set()` in other place but not inside the store itself , so now `.get()` renamed to `._get()` and `.set()` renamed to `._set()` .

So, _set is correct, but maybe the CI tools did not build everywhere to most updated status.

please run `npm install ../..` before you `npm start` when current directory is examples/04-infinite-scroll, I think this step can resolve this error.

If these steps can not fix this issue, just let me know, thanks.
